---
- hosts: linux
  become: true
 
  tasks:
    
    - name: Install Java
      include_role:
        name: install_java
        
    - name: Install git
      include_role:
        name: install_git
    
    - name: Install Docker
      include_role:
        name: install_docker
    
    
    